theme: jekyll-theme-slate
title: <a href="http://bellacode.github.io" class="bellacode-link"><span class="bellacode-bella">Bella</span><span class="bellacode-code">Code</span></a>
description: by Geoff Cox